requires:
- category: "seed"
  name: "funtoo-kits"
  version: ">=0"
env:
- JOBS=10
prelude:
- >-
  cp -rvf package.use /etc/portage/ &&
  cp -v make.conf /etc/portage &&
  cp -rvf patches /etc/portage/ &&
  epro flavor minimal &&
  epro mix-in +btrfs +vmware-guest &&
  epro list
#steps:
- >-
  emerge --unmerge
  sys-fs/lvm2
  virtual/udev
  virtual/libudev
  virtual/dev-manager
  virtual/service-manager
  sys-apps/gentoo-systemd-integration
  sys-apps/sysvinit
  sys-fs/eudev
  net-dns/openresolv
  sys-apps/corenetwork
  sys-apps/opentmpfiles
  virtual/udev
  virtual/tmpfiles
  sys-apps/openrc
  net-misc/dhcpcd
  sys-apps/usbutils
  sys-apps/pciutils
  sys-fs/dosfstools
  &&
  export FEATURES="-collision-protect -sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox" &&
  emerge -1 -t -j $JOBS sys-apps/systemd &&
  emerge -1uDN -t -j $JOBS @system &&
  emerge -t -j $JOBS -D @world &&
  emerge -t -j $JOBS dev-util/cmake dev-python/zipp &&
  rm -rf /var/cache/portage/distfiles/*
