env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages"
- LUET_PORTAGE_IGNORE_TAR_WARNING=1
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_PKGFILES=1
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet-portage
  --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages"
  ) }}
- rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true
- |
  eval 'mkdir /pkgdir/{{ .Values.name }}/etc/ld.so.conf.d -p || true' && \
  export GCC_VERSION={{ ( index .Values.labels "original.package.slot" ) }} && \
  echo "
  /usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_VERSION}/32
  /usr/lib/gcc/x86_64-pc-linux-gnu/${GCC_VERSION}
  " > /pkgdir/{{ .Values.name }}/etc/ld.so.conf.d/05gcc-${GCC_VERSION}-x86_64-pc-linux-gnu.conf
package_dir: /pkgdir/{{ .Values.name }}
excludes:
- ^/var/cache/portage/
- ^/var/git/
requires:
- name: funtoo-base
  version: '>=0'
  category: seed
