requires:
- category: "seed"
  name: "macaroni-funtoo-base"
  version: ">=0"
prelude:
- >-
  luet repo update &&
  luet i toolchain/meta-geaaru-kit --force &&
  luet cleanup &&
  rm /etc/localtime &&
  ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime
