env:
- JOBS={{ ( index .Values.labels "jobs" ) | default "3" }}
- LUET_PORTAGE_CACHE_PACKAGES="/var/cache/portage/packages"
- LUET_PORTAGE_IGNORE_TAR_WARNING=1
- LUET_PORTAGE_PKGMETA=1
- LUET_PORTAGE_PKGFILES=1
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- >-
  luet repo update &&
  luet install kernel-5.10/macaroni-lts-sources dev-util/kbuild --nodeps &&
  luet cleanup &&
  cd /usr/src && eval 'rm linux || true' &&
  KERNEL_VERSION=$(ls /usr/src/ -1 | grep macaroni | head -n 1 | cut -d'-' -f2) &&
  ln -s linux-${KERNEL_VERSION}-macaroni linux
- |
  eval 'mkdir -p /var/cache/portage/distfiles || true' && \
  chown portage:portage -R /var/cache/portage/ && \
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} --nodeps {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- eval 'rm -rf /pkgdir/ || true' && mkdir -p /pkgdir/{{ .Values.name }} && luet-portage
  --dir /pkgdir/{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
- rm -v /var/cache/distfiles/* ${LUET_PORTAGE_CACHE_PACKAGES}/* || true
package_dir: /pkgdir/{{ .Values.name }}
excludes:
- ^/var/cache/portage/
- ^/var/git/
requires:
- name: macaroni-funtoo-race4
  version: '>=0'
  category: seed
